
CREATE TABLE `to_content` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL DEFAULT '',
  `content` LONGTEXT,
  `view_num` INT NOT NULL DEFAULT 0,
  `createtime` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modifytime` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY  (`id`)
) ENGINE=MYISAM DEFAULT CHARSET=utf8;

CREATE TABLE `to_rel` (
  `cid` INT NOT NULL ,
  `mid` INT NOT NULL ,
  PRIMARY KEY  (`cid`,`mid`)
) ENGINE=MYISAM DEFAULT CHARSET=utf8;

CREATE TABLE `to_metas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL DEFAULT '',
  `type` VARCHAR(10) NOT NULL DEFAULT 'category',
  PRIMARY KEY  (`id`)
) ENGINE=MYISAM DEFAULT CHARSET=utf8;

CREATE TABLE `to_admin` (
  `username` VARCHAR(40) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  PRIMARY KEY  (`username`)
) ENGINE=MYISAM DEFAULT CHARSET=utf8;